server:
  port: 8082
spring:
  mail:
    # 邮件服务器地址
    host: smtp.163.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: UTF-8
    # 授权码
    password: KPSBWBGPILGUXHBR
    # 发送邮箱地址
    username: zhouzhijun720@163.com
    # 端口
    port: 25
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672