server:
  port: 8082
spring:
  redis:
    host: 192.168.109.156
    port: 6379
    # 超时时间
    timeout: 10000ms
    password: root
    database: 3
    lettuce:
      pool:
        # 最大连接数
        max-active: 1024
        # 最大连接阻塞等待时间，默认 -1
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5
  mail:
    # 邮件服务器地址
    host: smtp.163.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: UTF-8
    # 授权码
    password: KPSBWBGPILGUXHBR
    # 发送邮箱地址
    username: zhouzhijun720@163.com
    # 端口
    port: 25
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    listener:
      simple:
        # 开启手动确认
        acknowledge-mode: manual